---
title: "Using FLORAL with phyloseq data"
date: "2024-10-25"
output:
  rmarkdown::html_vignette:
    md_extensions: [ 
      "-autolink_bare_uris" 
    ]
vignette: >
  %\VignetteIndexEntry{Using FLORAL with phyloseq data}
  %\VignetteEncoding{UTF-8}
  %\VignetteEngine{knitr::rmarkdown}
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(phyloseq)
```

```{r}
#this file has duplicate rows, and has multiple rows per pool
samples <- read.csv("https://figshare.com/ndownloader/files/33076496") %>% distinct() %>% 
  select(-Pool, -Run, -ShotgunBatchID) %>% distinct()
metadata <-  read.csv("https://figshare.com/ndownloader/files/26770931")
counts <- read.csv("https://figshare.com/ndownloader/files/26393788") 
taxonomy <- read.csv("https://figshare.com/ndownloader/files/26770997")



phy <- phyloseq(
  sample_data(samples %>% column_to_rownames("SampleID")),
  tax_table(taxonomy %>% select(ASV, Kingdom:Genus) %>% column_to_rownames("ASV") %>% as.matrix()),
  otu_table(counts  %>% pivot_wider(names_from = "SampleID", values_from = "Count", values_fill = 0) %>% column_to_rownames("ASV") %>% as.matrix(), taxa_are_rows = TRUE)
) %>%  subset_samples(DayRelativeToNearestHCT > -30 & DayRelativeToNearestHCT < 30) 


dat <- FLORAL::phy_to_floral_data(phy, y=c("BioProject", "Timepoint"), covariates = covariates)

res <- FLORAL::FLORAL(y = dat$y, x = dat$xcount, ncov = dat$ncov, family = "gaussian")

```