# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

softthreshold <- function(x, lambda) {
    .Call('_LogRatioReg_softthreshold', PACKAGE = 'LogRatioReg', x, lambda)
}

gd_naive <- function(x, y, l, beta) {
    .Call('_LogRatioReg_gd_naive', PACKAGE = 'LogRatioReg', x, y, l, beta)
}

gd_cov <- function(xx, xy, n, l, beta) {
    .Call('_LogRatioReg_gd_cov', PACKAGE = 'LogRatioReg', xx, xy, n, l, beta)
}

gd_cov_al <- function(xx, xy, n, l, beta, mu, alpha, intercept) {
    .Call('_LogRatioReg_gd_cov_al', PACKAGE = 'LogRatioReg', xx, xy, n, l, beta, mu, alpha, intercept)
}

linear_lasso <- function(x, y, len) {
    .Call('_LogRatioReg_linear_lasso', PACKAGE = 'LogRatioReg', x, y, len)
}

linear_lasso_al <- function(x, y, len, mu, ub, lambda, intercept) {
    .Call('_LogRatioReg_linear_lasso_al', PACKAGE = 'LogRatioReg', x, y, len, mu, ub, lambda, intercept)
}

logistic_lasso_al <- function(x, y, len, mu, ub, lambda) {
    .Call('_LogRatioReg_logistic_lasso_al', PACKAGE = 'LogRatioReg', x, y, len, mu, ub, lambda)
}

cox_lasso_al <- function(x, t, d, tj, len, mu, ub, lambda, devnull) {
    .Call('_LogRatioReg_cox_lasso_al', PACKAGE = 'LogRatioReg', x, t, d, tj, len, mu, ub, lambda, devnull)
}

